version: '3'

volumes:
  my_flashcards_local_postgres_data: {}
  my_flashcards_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: my_flashcards_local_django
    container_name: my_flashcards_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: my_flashcards_production_postgres
    container_name: my_flashcards_local_postgres
    volumes:
      - my_flashcards_local_postgres_data:/var/lib/postgresql/data
      - my_flashcards_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: my_flashcards_local_docs
    container_name: my_flashcards_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./my_flashcards:/app/my_flashcards:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: my_flashcards_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: my_flashcards_local_redis

  celeryworker:
    <<: *django
    image: my_flashcards_local_celeryworker
    container_name: my_flashcards_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: my_flashcards_local_celerybeat
    container_name: my_flashcards_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: my_flashcards_local_flower
    container_name: my_flashcards_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
    environment:
      - FLOWER_BASIC_AUTH=username:password

  react:
    image: vite-react
    stdin_open: true
    container_name: my_flashcards_local_react
    build:
      context: .
      dockerfile: ./compose/local/react/Dockerfile
    depends_on:
      - django
      - postgres
    volumes:
      - "./my_flashcards_frontend:/app"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
