# Generated by Django 4.2.11 on 2025-08-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multipleexercisesitem',
            name='multiple_exercises',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_items', to='exercises.multipleexercises'),
        ),
        migrations.AddField(
            model_name='flexibleexercisepage',
            name='embedded_exercise',
            field=models.ForeignKey(blank=True, help_text='Main exercise for this page', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embedded_in_flexible_pages', to='exercises.exercisebase'),
        ),
        migrations.CreateModel(
            name='FillInTextExerciseWithChoicesWithImageDecoration',
            fields=[
                ('fillintextexercisewithchoices_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exercises.fillintextexercisewithchoices')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('exercises.fillintextexercisewithchoices',),
        ),
    ]
