# Generated by Django 4.2.11 on 2025-08-17 13:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('popularity', models.IntegerField(default=0, editable=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField(default=0, editable=False)),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LEARN', 'LEARN'), ('BROWSE', 'BROWSE'), ('BROWSE_AND_LEARN', 'BROWSE_AND_LEARN')], default='LEARN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('front_side', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, message='The field must contain at least 2 characters')], verbose_name='Front side')),
                ('back_side', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, message='The field must contain at least 2 characters')], verbose_name='Back side')),
                ('is_correct', models.BooleanField(default=True)),
                ('next_learn', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)])),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
