# Generated by Django 4.2.11 on 2024-03-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_deck_user_word_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
