# Generated by Django 4.2.11 on 2024-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_deck_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='words',
            field=models.ManyToManyField(blank=True, to='flashcards.word'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
