# Generated by Django 4.2.11 on 2024-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_deck_words_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
