# Generated by Django 4.2.11 on 2024-03-21 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_deck_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={},
        ),
        migrations.AddField(
            model_name='deck',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='popularity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='back_side',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, message='Pole musi zawierać co najmniej 2 znaki')]),
        ),
        migrations.AlterField(
            model_name='word',
            name='front_side',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, message='Pole musi zawierać co najmniej 2 znaki')]),
        ),
    ]
