# Generated by Django 4.2.11 on 2024-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_deck_options_deck_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='popularity',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
