# Generated by Django 4.2.11 on 2024-03-24 20:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0008_tempfilewords_tempfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LEARN', 'LEARN'), ('BROWSE', 'BROWSE'), ('BROWSE_AND_LEARN', 'BROWSE_AND_LEARN')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='words',
            field=models.ManyToManyField(blank=True, to='flashcards.word', verbose_name='Words'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='word',
            name='back_side',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, message='The field must contain at least 2 characters')], verbose_name='Back side'),
        ),
        migrations.AlterField(
            model_name='word',
            name='front_side',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, message='The field must contain at least 2 characters')], verbose_name='Front side'),
        ),
        migrations.DeleteModel(
            name='TempFile',
        ),
        migrations.DeleteModel(
            name='TempFileWords',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='correct_flashcards',
            field=models.ManyToManyField(related_name='correct_user_history', to='flashcards.word'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.deck'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
