# Generated by Django 4.2.11 on 2024-03-25 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_alter_word_next_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='next_learn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
