# Generated by Django 4.2.11 on 2024-04-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_word_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='deck_words', to='flashcards.word', verbose_name='Words'),
        ),
    ]
