# Generated by Django 4.2.11 on 2024-05-05 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_alter_deck_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
