#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mkdir -p /app/backend/production-static
chown -R "$(id -u):$(id -g)" /app/backend/production-static

python /app/manage.py collectstatic --noinput
python manage.py migrate
exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
